[tool.ruff]
# Set a standard line length
line-length = 88
# Assume Python 3.10+
target-version = "py310"
# A good starting set of rules:
# E, F: standard pyflakes errors/warnings
# W: pycodestyle warnings
# I: isort (import sorting)
# C90: mccabe complexity checks
select = ["E", "F", "W", "I", "C90"]
ignore = []
# Configure isort rules under ruff
src = ["src", "tests"]
exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".venv",
    "*.pyc",
    "dist"
]


[tool.pyright]
venvPath = "."
venv = ".venv"  # Or your virtual environment name
include = ["src", "notebooks"]
exclude = ["**/__pycache__", ".ruff_cache", "**/.*", "**/.ipynb_checkpoints"]
typeCheckingMode = "basic"
reportMissingImports = true
reportUnusedVariable = true
reportPossiblyUnboundVariable = true
reportGeneralTypeIssues = true
pythonVersion = "3.10" # Match your project's Python version

# Helps pyright find your local packages, treating 'src' as a root for 'clarity'
executionEnvironments = [
  { root = "src" }
]
