[tool.ruff]
# Set a standard line length
line-length = 88
# Assume Python 3.10+
target-version = "py310"
# A good starting set of rules:
# E, F: standard pyflakes errors/warnings
# W: pycodestyle warnings
# I: isort (import sorting)
# C90: mccabe complexity checks
select = ["E", "F", "W", "I", "C90"]
ignore = []
# Configure isort rules under ruff
src = ["src", "tests"]
exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".venv",
    "*.pyc",
    "dist"
]

# Per-file ignores for specific directories
[tool.ruff.per-file-ignores]
"notebooks/*.py" = ["E501"]
"tests/*.py" = ["E501"]



[tool.pyright]
venvPath = "."
venv = ".venv"
typeCheckingMode = "basic"
reportMissingImports = true
reportMissingTypeStubs = false
exclude = ["**/__pycache__", "**/.ipynb_checkpoints", "**/.pytest_cache"]

# Explicitly list modules to ignore missing type stubs for
pyrightIgnoreModules = ["mne", "pywt", "scipy", "scipy.signal", "sklearn", "sklearn.metrics", "tqdm", "setuptools"]

# Helps pyright find your local packages, treating 'src' as a root for 'clarity'
executionEnvironments = [
  { root = "src" }
]
